[package]
name = "client"
version = "0.1.0"
edition = "2021"

[lib]
name = "bulkistore_client"
crate-type = ["cdylib"]

[dependencies]
commons = { path = "../commons" }
tonic = "0.12.3"
prost = "0.13.4"
tokio = { version = "1", features = ["full"] }
mpi = "0.8.0"
hostname = "0.4.0"
uuid = { version = "1.4.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
rmp-serde = "1.1"
rand = "0.8"
pyo3 = { version = "0.23.4", features = ["extension-module"] }

[[bin]]
name = "bulkistore-client"
path = "src/client.rs"
