[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bkstore_client"
crate-type = ["cdylib"]


[dependencies]
commons = { path = "../commons" }
tonic = "0.12.3"
prost = "0.13.4"
tokio = { version = "1", features = ["full"] }
hostname = "0.4.0"
uuid = { version = "1.4.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
rmp-serde = "1.1"
rand = "0.8"
pyo3 = { version = "0.20.0", features = ["extension-module", "abi3-py37"] }
pyo3-asyncio = { version = "0.20.0", features = [
    "attributes",
    "tokio-runtime",
] }
log = { workspace = true }
anyhow = { workspace = true }
ndarray = { workspace = true }
mpi = { version = "0.8.0", optional = true }

[features]
default = ["mpi"]
mpi = ["dep:mpi", "commons/mpi"]

# [target.aarch64-apple-darwin]
# rustflags = [
#     "-C",
#     "link-arg=-undefined",
#     "-C",
#     "link-arg=dynamic_lookup",
#     "-C",
#     "link-arg=-Wl,-rpath,/opt/homebrew/Caskroom/miniconda/base/lib",
# ]

# [build]
# rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]

[[bin]]
name = "bulkistore-client"
path = "src/client.rs"
