[package]
name = "bulkistore-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bulkistore-commons = { path = "../commons" }
tonic = "0.12.3"
prost = "0.13.4"
tokio = { version = "1", features = ["full"] }
mpi = "0.8.0"
hostname = "0.4.0"
uuid = { version = "1.4.1", features = ["v4", "fast-rng", "macro-diagnostics"] }

[[bin]]
name = "bulkistore-client"
path = "src/client.rs"
