[workspace]
members = ["commons", "server", "client"]
resolver = "2"

[workspace.dependencies]
mpi = { version = "0.8.0" }
log = { version = "0.4.25" }
anyhow = { version = "1.0" }
bincode = { version = "1.3.3" }
rmp-serde = { version = "1.1" }
serde = { version = "1.0", features = ["derive"] }
rand = { version = "0.8" }

[workspace.features]
default = ["mpi"]
mpi = []

[profile.release]
lto = true
strip = true
opt-level = 3

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 0

[profile.bench]
opt-level = 3
