[workspace]
members = ["commons", "server", "client"]

[workspace.dependencies]
mpi = { version = "0.8.0", optional = true }
log = { version = "0.4.25" }

[workspace.features]
default = ["mpi"]
mpi = ["dep:mpi"]

[profile.release]
lto = true
strip = true
opt-level = 3

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 0

[profile.bench]
opt-level = 3
