[workspace]
members = ["commons-macros", "commons", "server", "client"]
resolver = "2"

[workspace.dependencies]
mpi = { version = "0.8.0" }
log = { version = "0.4.25" }
anyhow = { version = "1.0" }
rmp-serde = { version = "1.1" }
serde = { version = "1.0", features = ["derive"] }
rand = { version = "0.8" }
ndarray = { version = "0.16.1" }
syn = { version = "2.0.96", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.93"
inventory = "0.3"

[workspace.features]
default = ["mpi"]
mpi = []

[profile.release]
lto = true
strip = true
opt-level = 3

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 0

[profile.bench]
opt-level = 3
