[package]
name = "commons"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.3"
prost = "0.13.4"
tokio = { version = "1", features = ["full"] }
hostname = "0.4.0"
mpi = { workspace = true, optional = true }
log = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true, features = ["derive"] }
rand = { workspace = true }

[build-dependencies]
tonic-build = "0.12.3"

[features]
default = []
mpi = ["dep:mpi"]
