[package]
name = "commons-macros"
version = "0.1.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
inventory = { workspace = true }
